
server:
  port: 8799

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      user.name: admin
      user.password: 123456
    easeRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    ip-address: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}


spring:
  application:
    name: admin
  security:
    user:
      name: admin
      password: 123456
  boot:
    admin:
      ui:
        title: 监控系统


management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: ALWAYS

