server:
  port: 8762
spring:
  application:
    name: course

#配置服务
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config

#服务发现与监测
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/

#配置feign
feign:
  hystrix:
    enabled: true

#监控端口
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
