
server:
  port: 8763
spring:
  application:
    name: msg

#配置服务
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config


  mail:
    host: smtp.qq.com # 设置邮箱主机
    username:
    password:   # 设置密码，该处的密码是QQ邮箱开启SMTP的授权码而非QQ密码
#    properties: {mail.smtp.auth:true,mail.smtp.starttls.enable:true,mail.smtp.starttls.required:true}


#服务发现与监测
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/

#监控端口
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
