
server:
  port: 8080

spring:
  application:
    name: getway

  #网关配置
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

#服务注册发现
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 40 #告诉服务端，如果我20s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-renewal-interval-in-seconds: 20 #每间隔10s，向服务端发送一次心跳，证明自己依然”存活“

#监控端点
#management:
#    endpoints:
#      web:
#        exposure:
#          include: "*"
#    endpoint:
#      health:
#        show-details: ALWAYS
