
server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chenyixin8854/config
          search-paths: quark
          username:
          password:
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/