
server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/

spring:
  application:
    name: auth

  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config



